### ISSUE TITLE
Scanning with cost=false produces an xlsx not importable into pbit

### ISSUE THREAD

**Issue by red-erik** [Azure/azqr#257]
Hello,
running preview 8 and all errors related to timeouts or hangs seem to be solved, thanks.
Now, I'd like to know how to properly import xlsx into pbit when using "cost=false" switch during the scan
since BI Desktop gives errors for "missing data".

![image](https://github.com/user-attachments/assets/fbb0f797-ff42-4605-b5b2-0b5ccaf4c3b9)

Regards,
Red.

**Comment by cmendible** [comment]
`v.2.0.0-preview.9` should fix it 😊

**Comment by red-erik** [comment]
Hello,
still having problems

![image](https://github.com/user-attachments/assets/946aca37-b5ec-470a-adef-17d9cc11aa8c)

![image](https://github.com/user-attachments/assets/71c79343-2adc-45a5-87cc-20ed467f76de)

![image](https://github.com/user-attachments/assets/cb304123-220e-4824-85ab-39144d911956)


Regards,
Red.

**Comment by cmendible** [comment]
Sorry about that, give me some time and I'll check it by EOD

**Comment by cmendible** [comment]
Check v.2.0.0-preview.10

**Comment by red-erik** [comment]
Hello,
on preview 10 I have

![image](https://github.com/user-attachments/assets/353973d2-ae27-4c0c-8da4-9006ac299246)

and clicking on "view erros" I receive this

![image](https://github.com/user-attachments/assets/a1b78575-7e13-429f-adc0-0f028ff816a5)


Regards,
Red.

**Comment by cmendible** [comment]
I can't repro that one. Can you somehow anonymize the data and share it with me?

**Comment by red-erik** [comment]
Hello,
it worked, at the end. Not sure if the BI report is really complete, but thanks.

Regards,
Red.
